<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        padding: 50
        spacing: 20

        Button:
            text: "Hello World"

        Button:
            text: "GOOD  World"

        Button:
            text: "BYE World"
            pos_hint: {'center_x': .5}
            size_hint: (0.5, 0.5)
            width: 100
            height: 50

